### ISSUE TITLE
Response status 201 is viewed error

### ISSUE THREAD

**Issue by darkamenosa** [koltyakov/gosip#12]
I got trouble with the response status while using the lib. After an hour debugging, I found a little code the in lib: 

```
	if err == nil && resp.StatusCode != 200 {
		err = fmt.Errorf("%s", resp.Status)
	}
```

Why did you do that? Can I know the reason?

In my case, the response status was 201, and the lib considered it as an error. I think we should change it to:

```
	if err == nil && !(resp.StatusCode >= 200 && resp.StatusCode < 300) {
		err = fmt.Errorf("%s", resp.Status)
	}
```

**Comment by koltyakov** [comment]
Thanks, @darkamenosa! Looks like a valid change. Pushed this to the codebase.
