### ISSUE TITLE
XML syntax error

### ISSUE THREAD

**Issue by brudnak** [koltyakov/gosip#21]
Hello,

I'm getting the following error, I'm sure it's not a bug but could use some help figuring out the problem.

```sh
2020/01/21 14:11:04 unable to request api: XML syntax error on line 53: element <meta> closed by </head>
```

When running the following code

```go
package main

import (
	"fmt"
	"github.com/koltyakov/gosip"
	"github.com/koltyakov/gosip/api"
	strategy "github.com/koltyakov/gosip/auth/saml"
	"log"
)

func main() {

	authCnfg := &strategy.AuthCnfg{}
	configPath := "./config/private.json"
	if err := authCnfg.ReadConfig(configPath); err != nil {
		log.Fatalf("unable to get config: %v", err)
	}

	client := &gosip.SPClient{AuthCnfg: authCnfg}
	sp := api.NewSP(client)

	fmt.Printf("%T\n", sp)

	items, err := sp.Web().Lists().GetByTitle("SFM Regions").Items().Select("15,Bay Area").Get()
	fmt.Println("test")
	if err != nil {
		log.Fatal(err)
	}

	for _, item := range items.Data() {
		fmt.Println(item.Data().Title)
	}
}
```

**Versions**
```sh
go version go1.13.5 windows/amd64
```
SharePoint Online

**To Reproduce**
I've tried many different examples, and keep getting the same error. My folder structure is as follows:

- project folder
    - config folder
        - private.json
    - main.go

my private.json file as follows (but with my real info)
```json
{
  "siteUrl": "https://contoso.sharepoint.com/sites/test",
  "username": "john.doe@contoso.onmicrosoft.com",
  "password": "this-is-not-a-real-password"
}
```

**Any Advice?**

**Comment by koltyakov** [comment]
Hi @brudnak,

Thanks for trying the library.

Regarding the issue, is there something special in the SharePoint Online environment configuration (MFA, custom ADFS provider, O365 Dedicated)?

Could you try [On-Demand](https://go.spflow.com/auth/custom-auth/on-demand) auth to be sure that this is auth-related? On-Demand opens the Chrome Browser window to prompt for creds. It's limited for dev scenarios but can expose some additional clues.

Regarding request sample (however, this is definitely not a cause of this error), `sp.Web().Lists().GetByTitle("SFM Regions").Items().Select("15,Bay Area").Get()` this has an issue (which will lead to API call error response. `Select("15,Bay Area")` - that part. In the select there should be a list of fields (entity type names, in most of the cases are equal to internal names), like `Select("Id,Title,Modified")`.

**Comment by brudnak** [comment]
Thank you @koltyakov for your reply and advice. I really appreciate it, it started working with the On-Demand auth, and turns out to be an issue with how my company has setup SharePoint.
