### ISSUE TITLE
Support for creating Site Collection 

### ISSUE THREAD

**Issue by swapnilgaonkar** [koltyakov/gosip#23]
I can't find API in your library to create new Site Collection.
There is API to create sub-site under particular site but no API to create Site collection

**Comment by koltyakov** [comment]
Hi @swapnilgaonkar, are you running SharePoint Online?

In SPO, we can handle this using [/_api/SPSiteManager](https://docs.microsoft.com/en-us/sharepoint/dev/apis/site-creation-rest) endpoint. However, if it's On-Prem it depends on the version, and not possible via client-side APIs in older SharePoint versions.

**Comment by koltyakov** [comment]
Added samples of Site Creation: https://github.com/koltyakov/gosip-sandbox/tree/master/samples/sites

**Comment by swapnilgaonkar** [comment]
Thanks for reply.
I am running SPO.
I have tried /_api/SPSiteManager. It can be used to create modern sites only(can not create classic sites. Failed with error "Performing this operation on a site with this template is not allowed"). Correct me if I am wrong

I am looking for API/method which can create all type of site collection(similar to 'tenant.CreateSite' in c# CSOM).
Do you think it will be possible to do it using Rest API similar to '/_api/SPSiteManager'

**Comment by koltyakov** [comment]
Classic site collections can only be created using Tenant API (CSOM, that you've mentioned), it's unlikely that something will appear in REST or Graph regarding Classic sites ever.
A Tenant site can be requested using `gosip`, CSOM [XML package can be constructed "manually"](https://github.com/pnp/office365-cli/blob/cd657ed0fbdd5bec319d846f2dce906390f28dc2/src/o365/spo/commands/site/site-classic-add.ts#L120), for example, if the aim is to avoid any .Net dependencies and have the feature in pure Go. The `site classic add` command from O365 CLI can be reproduced. And there is CSOM requests helper ([example](https://github.com/koltyakov/gosip/blob/b417126eef39c9d4979f2d716b9540f2c7e1b190/api/properties.go#L142)) in `gosip` for workaround some REST API gaps. Though, I didn't have plans to extend `gosip` with any tenant-level APIs. As it can lead to serious efforts to add support for all management features while at the same time, true cross-platform tools such as Office 365 CLI already exist for management purposes. 

So, if it's single time automation I'd suggest mixing Go & other friendly technologies together. If a method which is entended being in a solution and only pure Go is appropriate without other prerequisites and dependencies, when [ProcessQuery helper](https://github.com/koltyakov/gosip/blob/b417126eef39c9d4979f2d716b9540f2c7e1b190/api/http.go#L194) and crafted CSOM XML package withing a custom method is a way to go.

**Comment by swapnilgaonkar** [comment]
Thanks,
I was able to create classic site using above suggestion related to CSOM XML package and CSOM requests helper

**Comment by swapnilgaonkar** [comment]
FYI, I have to modify ProcessQuery by adding code mentioned in bold.
This is necessory to avoid https://stackoverflow.com/questions/31398044/got-error-invalid-character-%C3%AF-looking-for-beginning-of-value-from-json-unmar
data, err := ioutil.ReadAll(resp.Body)
if err != nil {
	return nil, err
}
**data = bytes.TrimPrefix(data, []byte("\xef\xbb\xbf"))**

var arrRes []interface{}
if err := json.Unmarshal(data, &arrRes); err != nil {
	return data, err
}

**Comment by koltyakov** [comment]
Interesting. Maybe it's environment-specific as ProcessQuery's implementation is used in a number of places but no issues due to BOM prefix. Added BOM prefix removal to the codebase, at least it doesn't break anything with CSOM which worked before.

If you'd like, feel free to post a PR with an example for classic sites in SPO to [the sandbox project](https://github.com/koltyakov/gosip-sandbox/tree/master/samples), so we can reference it as a solution here for others to reuse.
