### ISSUE TITLE
Support for get all field values of items 

### ISSUE THREAD

**Issue by vimalraghwani** [koltyakov/gosip#24]
I am not able to find to get all the field values of each item. 
Can you provide the reference for the same if its already there.

Many thanks in Advance
RV.

**Comment by koltyakov** [comment]
Please check [this article](https://go.spflow.com/samples/unmarshaling-responses). To get all default field values you can omit `.Select` modifier or use `.Select("*")`, for example, if all default plus something specific should be requested (could be something from expanded properties, etc.) asterisk can be mixed with other props in select "*,Editor/EMail".

As code knows nothing about custom List structure, the expected payload should be described as a struct or interface{} or map and unmarshaled from JSON. `Normalized` helper is recommended here. `Data` helper unmarshales a response to a generic struct with bare minimal metadata footprint.

```golang
data, err := list.Items().Get() // it's always better to provide spefific fields to requests
if err != nil {
  log.Fatalln(err)
}

var items []map[string]interface{} // or struct whatever is prefered

// .Normalized() method aligns responses between different OData modes
if err := json.Unmarshal(data.Normalized(), &items); err != nil {
  log.Fatalf("unable to parse the response: %v", err)
}

fmt.Printf("%#v\n", items)
```

**Comment by vimalraghwani** [comment]
Thanks a lot for help.
