### ISSUE TITLE
How to get permission for lists and items 

### ISSUE THREAD

**Issue by vimalraghwani** [koltyakov/gosip#25]
I am trying to get the permission for each list and item.
i tried getting through Roles() method for list and item but unable to get.
Please provide the reference if  any.

Many thanks in Advance,
RV.

**Comment by koltyakov** [comment]
Did you read this [docs' article](https://go.spflow.com/samples/permissions)? It's mostly for managing permissions.

To get permissions in batches (for selected lists or items) `EffectiveBasePermissions` property can be used, however, it returns low and hight permissions hashes for a current user context.

What you asking sounds more like checking `RoleAssignments`:

```golang
sp := api.NewSP(client)
res, err := sp.Web().Lists().
  Select("RoleAssignments/Member/LoginName,RoleAssignments/RoleDefinitionBindings/Name").
  Expand("RoleAssignments/Member,RoleAssignments/RoleDefinitionBindings").
  Top(5).
  Get()

if err != nil {
  log.Fatal(err)
}

var lists []map[string]interface{}

if err := json.Unmarshal(res.Normalized(), &lists); err != nil {
  log.Fatalf("unable to parse the response: %v", err)
}

for _, l := range lists {
  fmt.Printf("%#v\n", l)
}
```

**Comment by koltyakov** [comment]
Just in case added a sample which can be handy for getting role assignments https://github.com/koltyakov/gosip-sandbox/tree/master/samples/permissions and some related helper methods as [HasPermissions](https://github.com/koltyakov/gosip/blob/master/api/permissions.go#L188) which can detect if an `EffectiveBasePermissions` contains specific [permission kind](https://github.com/koltyakov/gosip/blob/master/api/permissions.go#L22).

**Comment by vimalraghwani** [comment]
Thanks a lot buddy.

**Comment by vimalraghwani** [comment]
Hey, 
Sorry to disturb you again, but i tried the above sample application for the items and it failed with error

2020/05/18 14:04:40 unable to request api: 400 Bad Request :: {"error":{"code":"-1, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"The field or property 'HasUniqueRoleAssignments' does not exist."}}}

Any clue what is wrong i m trying.

**Comment by koltyakov** [comment]
My fault, I put `HasUniqueRoleAssignments` also into `.Expand()`, which works perfectly fine when getting lists but fails for other entities as list items. Please try removing it from expand modifier.

**Comment by vimalraghwani** [comment]
Thanks for response. I figured that during debug.
Will this sample works on individual list and item object?

**Comment by koltyakov** [comment]
Sure thing, it works on collections and specific items as well.
