### ISSUE TITLE
Not all role definitions are supported by 'GetByName' function

### ISSUE THREAD

**Issue by swapnilgaonkar** [koltyakov/gosip#27]
Function sp.Web().RoleDefinitions().GetByName() is working fine for (edit, read, Design) but it is not working for (Manage Hierarchy, Restricted Read, Restricted Interfaces for Translation). It fails with error 'value does not fall within the expected range'

Can you provide any help

**Comment by koltyakov** [comment]
Hi @swapnilgaonkar, 

You can try getting all roles and check which exists. For none existing role definitions it's expected to receive an error from the API.

```golang
rd, err := web.RoleDefinitions().Get()
if err != nil {
  t.Error(err)
}
for _, r := range rd {
  fmt.Println(r.Name)
}
```

**Comment by swapnilgaonkar** [comment]
Thanks for the reply and sorry for the delayed response.
It was issue from my side. Above functionality working as expected.
Thanks

**Comment by koltyakov** [comment]
Thanks for coming back with the update. Closing the issue.
