### ISSUE TITLE
api library error

### ISSUE THREAD

**Issue by brett0701** [koltyakov/gosip#32]
Getting the following error when getting the api module:

../../../go/src/github.com/koltyakov/gosip/api/permissions.go:199:13: invalid operation: num << perm (shift count type int64, must be unsigned integer)
../../../go/src/github.com/koltyakov/gosip/api/permissions.go:202:12: invalid operation: num << perm (shift count type int64, must be unsigned integer)

**Comment by koltyakov** [comment]
Hi @brett0701,

Could you please check what Go version you use?

**Comment by brett0701** [comment]
go1.12.9

macOS Mohave v 10.14..6

**Comment by brett0701** [comment]
I upgraded to go1.13.11(version we run in prod) and I was able to get it working.

**Comment by koltyakov** [comment]
Refactored the method. Now it works also for legacy 1.12. Not sure if it's ever needed as 1.14 and 1.15 are actual versions. Maybe in some CI/CD where the old version is installed as a prerequisite and can't be easily bumped at least to 1.13. Anyways, 1.12.9 is supported now.
