### ISSUE TITLE
Can't update list

### ISSUE THREAD

**Issue by tlightsky** [koltyakov/gosip#33]
**Describe the bug**
try with https://go.spflow.com/samples/basic-crud#updating-an-item

**Versions**
master

**Expected behavior**
update a list item

**Screenshots**
if not set id, it will just add an item,
if set id, it will fail with duplicate id:
![image](https://user-images.githubusercontent.com/429211/91831381-94810180-ec76-11ea-932c-48ce16f44911.png)

**Additional context**

**Comment by tlightsky** [comment]
it seems we need to use 
```
		_, err := list.Items().GetByID(item.Data().ID).Update(jsonstr)
```

doc might need be update

**Comment by koltyakov** [comment]
@tlightsky thanks! Fixed the docs page sample.
