### ISSUE TITLE
Copy and move some item inside document library

### ISSUE THREAD

**Issue by MisterFredy** [koltyakov/gosip#39]
maybe we can improve with copy and move 

this is reference https://www.sharepointed.com/2018/06/copy-or-move-folder-structure-in-sharepoint-using-csom/
in CSOM

**Comment by koltyakov** [comment]
Thanks, some methods are implemented, such as File.CopyTo and File.MoveTo.
Will take a look if some additional methods from the suggested list can be added (via REST calls).
CSOM API can be used, though I try minifying cases with CSOM as it's harder to maintain.

**Comment by MisterFredy** [comment]
thanks
