### ISSUE TITLE
document improvement

### ISSUE THREAD

**Issue by MisterFredy** [koltyakov/gosip#40]
Hi i want to request tutorial about using this library CRUD with whole project.because it's hard to understand for newbie

**Comment by koltyakov** [comment]
Have you seen docs? https://go.spflow.com/samples/basic-crud

**Comment by MisterFredy** [comment]
yup where i get sp.Web().GetList("Lists/MyList")? should i get client connection? it's hard to understand for me

**Comment by koltyakov** [comment]
It's a bit redundant repeating initiation in each article. Most of them assumes a reference to the same steps described [here](https://go.spflow.com/#usage-insights). Does it make more sense?

**Comment by koltyakov** [comment]
Added a separate article in samples with configuration and some notes https://go.spflow.com/samples/library-initiation

**Comment by MisterFredy** [comment]
ah thanks for suggestion but we must create forum to learn about this.because sometime im stuck when learning.
