### ISSUE TITLE
Support for access hosted app over AppContextSite.

### ISSUE THREAD

**Issue by zhangyangjing** [koltyakov/gosip#48]
Has any plan to support [AppContextSite](https://sharepoint.stackexchange.com/questions/55334/how-to-access-list-in-sharepoint-hosted-app) api?

**Comment by koltyakov** [comment]
Hi @zhangyangjing,

No, I had no such plans. I don't think it not achievable but have not been looking into this direction.

**Comment by zhangyangjing** [comment]
Thanks
