### ISSUE TITLE
missing oauth2 instructions

### ISSUE THREAD

**Issue by zubairk14** [koltyakov/gosip#53]
**Describe the bug**
The AddIn Only Auth section references that we can use OAuth bearer tokens for authenticating HTTP requests, but there's no example of an OAuth credential use...

```
// AuthCnfg - AddIn Only auth config structure
type AuthCnfg struct {
	// SPSite or SPWeb URL, which is the context target for the API calls
	SiteURL string `json:"siteUrl"`
	// Client ID obtained when registering the AddIn
	ClientID string `json:"clientId"`
	// Client Secret obtained when registering the AddIn
	ClientSecret string `json:"clientSecret"`
	// Your SharePoint Online tenant ID (optional)
	Realm string `json:"realm"`
}
```

**Versions**
ALL

**To Reproduce**
n/a 

**Expected behavior**
Expecting some field to pass in a bearer token. 

**Screenshots**
![image](https://user-images.githubusercontent.com/18369799/217083965-e2e11e6f-7a67-4189-bbb6-85be3ab96802.png)

**Additional context**

**Comment by koltyakov** [comment]
Hi @zubairk14,

Based on Client ID/Secret the AddIn Only strategy gets Bearer and uses it as an auth header.

If you already have a Bearer (e.g. retrieved with browser protocol automation) you can use it without other auth strategies.

E.g.:

```golang
package main

import (
	"fmt"
	"log"

	"github.com/koltyakov/gosip"
	"github.com/koltyakov/gosip/api"
	strategy "github.com/koltyakov/gosip/auth/anon"
)

func main() {

	auth := &strategy.AuthCnfg{}
	client := &gosip.SPClient{AuthCnfg: auth}

	sp := api.NewSP(client)
	sp.Conf(&api.RequestConfig{Headers: map[string]string{"Authorization": "Bearer eyJr...fq7w"}})

	res, err := sp.Web().Select("Title").Get()
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("%s\n", res.Data().Title)
}
```

It could be helpful if you describe what you're going to achieve.

**Comment by zubairk14** [comment]
Hi Andrew, thank you for the super fast response! 

I'm building a tool where users can link their SharePoint and perform a scan of their SharePoint resources. I don't imagine people will be interested in sharing their client secret directly, so I was hoping to use an OAuth2.0 flow (where a bearer token is generated). 

> If you already have a Bearer (e.g. retrieved with browser protocol automation) you can use it without other auth strategies.

How can we go about passing through the Bearer directly if the AuthCnfg struct is looking for a cert or client secret?

```type AuthCnfg struct {
	SiteURL  string `json:"siteUrl"`  // SPSite or SPWeb URL, which is the context target for the API calls
	TenantID string `json:"tenantId"` // Azure Tenant ID
	ClientID string `json:"clientId"` // Azure Client ID
	CertPath string `json:"certPath"` // Azure certificate (.pfx) file location, relative to config location or absolute
	CertPass string `json:"certPass"` // Azure certificate export password

	authorizer  autorest.Authorizer
	privateFile string
	masterKey   string
}```

**Comment by koltyakov** [comment]
I'd say to look at Azure Multi-tenant App. Azure auth strategy: [cert](https://go.spflow.com/auth/custom-auth/azure-certificate-auth), [device](https://go.spflow.com/auth/custom-auth/azure-device-flow).

**Comment by zubairk14** [comment]
is Azure Device Flow supported for SharePoint on-premises or only SharePoint Online (Cloud) ?

**Comment by koltyakov** [comment]
Yes, Azure AD auth can be only used with SPO, as far as I know.

**Comment by koltyakov** [comment]
Going to close it. Feel free to reopen if needed.

**Comment by zubairk14** [comment]
Hi Andrew, does your library require app permissions for auth instead of delegated permissions? Or both should work?
https://learn.microsoft.com/en-us/graph/auth/auth-concepts
