### ISSUE TITLE
SharePoint Token type is not allowed

### ISSUE THREAD

**Issue by edmundrotimi** [koltyakov/gosip#55]
I am using an authentication object but each time I try I get an '{"error":"invalid_request","error_description":"Token type is not allowed."}'

    auth := &strategy.AuthCnfg{
         SiteURL:      os.Getenv("SPAUTH_SITEURL"),
         ClientID:     os.Getenv("SPAUTH_CLIENTID"),
         ClientSecret: os.Getenv("SPAUTH_CLIENTSECRET"),
    }

I have registered the new app using https://{site}/_layouts/15/AppRegNew.aspx and given full permission to the app using https://{site}/_layouts/15/appinv.aspx

     <AppPermissionRequests AllowAppOnlyPolicy="true">
        <AppPermissionRequest Scope="http://sharepoint/content/sitecollection" 
         Right="FullControl" />
     </AppPermissionRequests>

I can likewise see the app is available in the Site App Permission list using https://{site}/_layouts/15/appprincipals.aspx and I can use the client id and client secret in postman without error.

**Comment by koltyakov** [comment]
Hey @edmundrotimi could it be [this](https://learn.microsoft.com/en-us/answers/questions/714147/token-type-is-not-allowed-error-on-sharepoint-rest)?

**Comment by koltyakov** [comment]
Added this info to the [docs](https://go.spflow.com/auth/strategies/addin#known-issues).

**Comment by edmundrotimi** [comment]
Thanks, @koltyakov and @jhoelzel, for the reply. When I eventually deploy, will I need to apply this fix to a Linux environment?

**Comment by koltyakov** [comment]
Nothing to do with the library or your solution, it's SharePoint tenant configuration.

**Comment by edmundrotimi** [comment]
@koltyakov  I implemented the fix but cannot connect to the API. Each time I try to add a folder, I get the error "unable to request API: 403 Forbidden:: {"error":{"code":"-2147024891, System.UnauthorizedAccessException", "message":{"lang": "en-US", "value": "Access denied."}}}" but when I try: res, err := SPInstance.Web().Select("Title").Get() it works.

**Comment by edmundrotimi** [comment]
@jhoelzel to see the client created you can use https://<org_name>.sharepoint.com/sites/<sitte_name>/_layouts/15/appprincipals.aspx

**Comment by koltyakov** [comment]
Dummy question, are you sure you didn't generate AddIn creds by a user who has only read only permissions to actual content?

AddIn Only is trying to be dropped off by MS. If you start experiencing issues it could be time migrating to the recommended authentication via [Azure Apps](https://go.spflow.com/auth/strategies/azure-certificate-auth). If it's a dev-time experience or you can't go with Azure App configuration immediately [On-Demand auth](https://go.spflow.com/auth/strategies/on-demand) could work as an alternative.

I have not yet faced any issues with AddIn in my tenant, btw.

**Comment by koltyakov** [comment]
@edmundrotimi that's siteUrl parameter, not necessarily get it from env variables. It's site collection/site URL where you target the code to communicate with SharePoint API.

Same as here:

![image](https://user-images.githubusercontent.com/7816483/227568701-01e3bb97-32db-4746-bd16-4ab19700e09f.png)

On-Demand opens the site in anonymous browser session where you can authenticate with a user credentials, confirm 2FA if needed, when the popup closes and session token is passed to the code.

Keep in mind this technique work well when you can code from your local machine, for development time, not for headless jobs on a server.

**Comment by edmundrotimi** [comment]
@koltyakov thanks for the reply. I am still faced with the same error pattern despite using On-Deman login. I can access the site name using:
       client := &gosip.SPClient{AuthCnfg: auth}

       sp := api.NewSP(client)

       res, err := sp.Web().Select("Title").Get()
       if err != nil {
            fmt.Println(err)
       }

       fmt.Printf("%s\n", res.Data().Title)

However, each time I try to create a folder, I get the error "unable to request API: 403 Forbidden: {"error":{"code":"-2147024891, System.UnauthorizedAccessException", "message":{"lang": "en-US", "value": "Access denied."}}}".

**Comment by koltyakov** [comment]
Sounds you actually have no permissions for this action. Did you check you can do same action in UI?

**Comment by edmundrotimi** [comment]
@koltyakov I can create multiple folders and files from the UI.

**Comment by edmundrotimi** [comment]
@koltyakov I have double-checked the permission multiple times to confirm I have access.

**Comment by edmundrotimi** [comment]
@koltyakov sending it now. Thanks.

**Comment by edmundrotimi** [comment]
@koltyakov https://drive.google.com/file/d/14RCOaxhKfggQT3mknaH_K4tg1pbdn_JL/view?usp=share_link

**Comment by koltyakov** [comment]
Are you actually trying using this: `sharepoint.CreateFolder("parentPath", "folderName")`?

Parent path parameter which you then use in `sp.Web().GetFolder(parentPath)` will fail if the path doesn't stand for a valid `serverRelativeURL` of an existing folder. Check the samples out https://go.spflow.com/samples/documents#adding-new-folder.

Folders should only be created in SPFolder objects, it can't be a random path.

P.S. You leaked client/secret, so I removed your last message to avoid somebody taken the creds.  I'd recommend to remove the adding registration which was leaked.

**Comment by edmundrotimi** [comment]
Hi @koltyakov, thanks for the reply. I deleted the credentials already. I will check https://go.spflow.com/samples/documents#adding-new-folder. Thanks again.

**Comment by edmundrotimi** [comment]
@koltyakov since the GetFolder gets the file object that exists in SP already, why do the Folders().Add give an error if the parent folder already exists.

**Comment by koltyakov** [comment]
The folder path should be a correct server relative path of an existing folder in a document library.

Try this:

```go
randomParentFolder := uuid.New().String() // Random name so each time it pass the test

// Getting a common library will exclude the path is incorrect
docsRootFolder := sp.Web().Lists().GetByTitle("Documents").RootFolder()
parentFolder, err := docsRootFolder.Folders().Add(randomParentFolder)
if err != nil {
  log.Fatal(err)
}

// This is a sample of a path you need to provide to GetFolder() method
fmt.Printf("Parent folder relative path: %s\n", parentFolder.Data().ServerRelativeURL)

// Getting by the parent and creating a child
childFolder, err := sp.Web().GetFolder(parentFolder.Data().ServerRelativeURL).Folders().Add("childFolder")
if err != nil {
  log.Fatal(err)
}

// The path of a child folder
fmt.Printf("Child folder relative path: %s\n", childFolder.Data().ServerRelativeURL)

// Clean up test
if err := sp.Web().GetFolder(parentFolder.Data().ServerRelativeURL).Delete(); err != nil {
  log.Fatal(err)
}
```

<img width="747" alt="image" src="https://user-images.githubusercontent.com/7816483/227637457-094b4c46-e43d-409b-b36d-a2fc817d9bb8.png">

**Comment by edmundrotimi** [comment]
@koltyakov apart from the read operation, every order operation has not worked for me.

**Comment by edmundrotimi** [comment]
@koltyakov Thanks a lot for the help, your last message was really helpful.

**Comment by koltyakov** [comment]
So I guess AddIn also should work. My expectations is that you'we getting 403 while just constructing a resource path which doesn't exist or trying creating a folder outside a document library.

Going to close this. Thanks for using the library!
