### ISSUE TITLE
Digest Header

### ISSUE THREAD

**Issue by lbischof** [koltyakov/gosip#6]
I am using the `saml` authentication. To be able to write new files I needed to include the Digest value in the header:

POST request to `/_api/contextinfo` to retrieve the value and then set the header:
```
req.Header.Set("X-RequestDigest", "0x4C1XXXXXXXXXXXXXXXX,20 Mar 2019 12:26:18 -0000")
```
Maybe this could be documented or automated somehow?

**Comment by koltyakov** [comment]
Hi @lbischof,

Thanks for using the library.

Yes, it's a good idea to cover digest aspects and add more samples. Actually, it was in my plans. Probably I should add more samples and docs sooner.

I also plan to automate digest as a part of the client in the way as we do in PnPjs.

**Comment by koltyakov** [comment]
Intermediate update:

Created [digest helper](https://github.com/koltyakov/gosip/blob/master/digest.go). Which can be used as a [stand-alone operation](https://github.com/koltyakov/gosip/blob/master/cmd/samples/digest/main.go#L24). Also, the digest [is injected automatically](https://github.com/koltyakov/gosip/blob/master/gosip.go#L70) into POST requests and no need to provide it manually now.

As a sample, [add list's item operation](https://github.com/koltyakov/gosip/blob/master/cmd/samples/addListItem/main.go).

Documentation is still in work but should land soon into wiki section.

**Comment by lbischof** [comment]
Thanks!

**Comment by lbischof** [comment]
Just tested. Works perfectly!
