### ISSUE TITLE
Support special characters in EnsureFolder 

### ISSUE THREAD

**Issue by whiteboxsolutions** [koltyakov/gosip#63]
**Is your feature request related to a problem? Please describe.**
The current EnsureFolder method doesn't allow for the use of decodedURL (in the same vein as GetFolderByPath or GetFileByPath). This results in an inability to ensure that folders including special characters exist.

**Describe the solution you'd like**
Change the method to use GetFolderByPath instead of GetFolder

Submitting PR momentarily

**Comment by koltyakov** [comment]
Thank you. I will check. Yet from the first glance the PR doesn't look OK (some overwrite of Folders with Folder which feels weird and backward compatibility breaking is happening in the PR).

What special characters are you trying to use? I'd appreciate a few samples.

I'll better add test cases with special chars and make sure it works to start with.

**Comment by whiteboxsolutions** [comment]
Ah, it looks like my commit pulled in a bunch of pending changes on the dev branch - the only changes I made were to lines 189 and 209

I'll revoke and resubmit tonight

**Comment by koltyakov** [comment]
> The special characters I'm looking at are # and %

Thank you! I'll add them to tests and check it out over the weekend.

**Comment by koltyakov** [comment]
Hey @whiteboxsolutions,

Please try `web.EnsureFolderByPath` method it should support special characters in folder paths.

I kept `web.EnsureFolder` as is for backwards compatibility with SharePoint 2013.
