### ISSUE TITLE
Login to sharepoint with username/password and SiteURL

### ISSUE THREAD

**Issue by NguyenBaoXuanTruong** [koltyakov/gosip#7]
Hello,

I don't have ClientID and ClientSecret for Sharepoint, but I have username and password to login it. So, Can I use you lib to login Sharepoint by using username/password and SiteURL? Can you show me code examples for this? I only need to check the folder exist or not, create folder and upload files to this folder. Please help me.

Thank you

**Comment by koltyakov** [comment]
Hi @NguyenBaoXuanTruong,

Thanks for letting the library go in your project. 
Gosip supports a variety of authentication strategies and SharePoint versions.

Supported SharePoint versions:

- SharePoint Online (SPO)
- On-Prem: 2019, 2016, and 2013

Authentication strategies:

- SharePoint On-Premises 2019/2016/2013:
  - ADFS user credentials (ADFS, WAP -> Basic/NTLM, WAP -> ADFS)
  - Behind reverse proxy (TMG, WAP -> Basic/NTLM, WAP -> ADFS)
  - Form-based authentication (FBA)
- SharePoint Online:
  - Addin only permissions
  - SAML based with user credentials
  - ADFS user credentials

Based on a strategy applicable to your SharePoint version and configurations it can be different [auth module](https://github.com/koltyakov/gosip/tree/master/auth) to import.

Let's assume you work with SharePoint Online? In this case, you need `SAML` auth:

```golang
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"net/http"

	"github.com/koltyakov/gosip"
	strategy "github.com/koltyakov/gosip/auth/saml"
	// strategy "github.com/koltyakov/gosip/auth/ntml"
	// strategy "github.com/koltyakov/gosip/auth/adfs"
)

func main() {
	auth := &strategy.AuthCnfg{
		SiteURL:		os.Getenv("SPAUTH_SITEURL"),
		Username:	os.Getenv("SPAUTH_USERNAME"),
		Password:	os.Getenv("SPAUTH_PASSWORD"),
	}

	client := &gosip.SPClient{
		AuthCnfg: auth,
	}
}
```

**Comment by NguyenBaoXuanTruong** [comment]
Thank you @koltyakov I work for me 💯

**Comment by koltyakov** [comment]
Cool!

**Comment by NguyenBaoXuanTruong** [comment]
I really like your library. I really admire what you did.
