### ISSUE TITLE
Change Content Type and set props

### ISSUE THREAD

**Issue by phhoef** [koltyakov/gosip#73]
I am uploading a file to SPO and I want to change the document type and set a few specific props of that type.
Setting the props are completely ignored, though no error is returned.

```go
	file := web.GetFileByID(item.UniqueId)

	err := file.Props().SetProps(map[string]string{
		SPO_CONTENT_TYPE_ID:  t.StringId,
		"Source":                              "source",
		"Name":                                "blabla",
	})
```

Neither the ContentTypeId changed nor the properties are applied.
Is something wrong with my code?

**Comment by koltyakov** [comment]
I believe you should update list item instead of files property bags.

Something like:

```golang
item, err := web.GetFile("/Shared Documents/A File.txt").GetItem()
if err != nil {
  t.Error(err)
}
_, err = item.Update([]byte(`{
  "ContentTypeId": "0x010100B4CBD48E8F4F4BA4B8DCCD2A6A7A3E6A",
  "Title": "Updated Title"
}`))
```

**Comment by phhoef** [comment]
thanks @koltyakov! That was exactly, I was looking for 😄 works like a charm ...
